/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package almoxarifadoger.view.crud;

import almoxarifadoger.controller.DAOAlmoxarifado;
import almoxarifadoger.controller.DAOItem;
import almoxarifadoger.controller.DAOMovimento;
import almoxarifadoger.controller.DAOResponsavel;
import almoxarifadoger.model.Almoxarifado;
import almoxarifadoger.model.Item;
import almoxarifadoger.model.ItemAlmoxarifado;
import almoxarifadoger.model.MovimentoItemAlmox;
import almoxarifadoger.model.Responsavel;
import java.util.List;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JRootPane;

/**
 *
 * @author gustavo
 */
public class DialogCrudMovimento extends javax.swing.JDialog {

    MovimentoItemAlmox registroEmEdicao;

    /**
     * Creates new form DialogCrudMovimento
     */
    public DialogCrudMovimento(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        carregaItems();
        carregaResponsaveis();
        carregaAlmoxarifado();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jcbItem = new javax.swing.JComboBox<>();
        jcbAlmox = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jcbResp = new javax.swing.JComboBox<>();
        jcbTipo = new javax.swing.JComboBox<>();
        jLabel4 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setText("Item");

        jLabel2.setText("Almoxarifado");

        jLabel3.setText("Responsável");

        jcbTipo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Entrada", "Saida" }));

        jLabel4.setText("Tipo");

        jButton1.setText("Salvar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jcbItem, javax.swing.GroupLayout.PREFERRED_SIZE, 457, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, 122, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jcbAlmox, javax.swing.GroupLayout.PREFERRED_SIZE, 457, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, 122, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jcbResp, javax.swing.GroupLayout.PREFERRED_SIZE, 457, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, 122, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jcbTipo, javax.swing.GroupLayout.PREFERRED_SIZE, 457, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(42, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jcbResp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jcbItem, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jcbAlmox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jcbTipo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        getDadosDaTela();
        DAOMovimento daoM = new DAOMovimento();
        daoM.save(registroEmEdicao);
        this.dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    private void carregaItems() {
        DAOItem daoI = new DAOItem();
        List<Item> items = daoI.read("");
        DefaultComboBoxModel m = (DefaultComboBoxModel) jcbItem.getModel();
        m.removeAllElements();
        if (!items.isEmpty()) {
            for (Item i : items) {
                m.addElement(i);
            }
        }
    }

    private void carregaResponsaveis() {
        DAOResponsavel daoR = new DAOResponsavel();
        List<Responsavel> responsaveis = daoR.read("");
        DefaultComboBoxModel m = (DefaultComboBoxModel) jcbResp.getModel();
        m.removeAllElements();
        if (!responsaveis.isEmpty()) {
            for (Responsavel i : responsaveis) {
                m.addElement(i);
            }
        }
    }

    private void carregaAlmoxarifado() {
        DAOAlmoxarifado daoA = new DAOAlmoxarifado();
        List<Almoxarifado> almoxarifado = daoA.read("");
        DefaultComboBoxModel m = (DefaultComboBoxModel) jcbAlmox.getModel();
        m.removeAllElements();
        if (!almoxarifado.isEmpty()) {
            for (Almoxarifado i : almoxarifado) {
                m.addElement(i);
            }
        }
    }

    private void getDadosDaTela() {
        registroEmEdicao = new MovimentoItemAlmox();
        registroEmEdicao.setData(System.currentTimeMillis());
        registroEmEdicao.setTipo(jcbTipo.getSelectedIndex());
        ItemAlmoxarifado iA = new ItemAlmoxarifado();
        if (jcbAlmox.getItemCount() > 0) {
            iA.setAlmoxarifado((Almoxarifado) jcbAlmox.getSelectedItem());
        }
        if (jcbItem.getItemCount() > 0) {
            iA.setItem((Item) jcbItem.getSelectedItem());
        }
        registroEmEdicao.setItemAlmox(iA);
        if (jcbResp.getItemCount() > 0) {
            registroEmEdicao.setResponsavel((Responsavel) jcbResp.getSelectedItem());
        }
        
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JComboBox<Almoxarifado> jcbAlmox;
    private javax.swing.JComboBox<Item> jcbItem;
    private javax.swing.JComboBox<Responsavel> jcbResp;
    private javax.swing.JComboBox<String> jcbTipo;
    // End of variables declaration//GEN-END:variables
}
